# camera parameters for src/gnm_locobot.launch
# video_device: "/dev/video0" # change this to your video device path
image_width: 1280 
image_height: 720 
pixel_format: R8G8B8
camera_frame_id: "turtlebot_camera"
# io_method: "mmap"
framerate: 20